spring:
  application:
    name: guess_random_number
  datasource:
    url: jdbc:postgresql://localhost:5332/game
    username: rouchdane
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8081